### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheByteSizeDev**
FIXED:
Readme

### CODE REVIEW

**Review by MelanieJaneBond — COMMENTED** [review]
👍 
I LOVE IT! HAHA

**Review by joekennerly — CHANGES_REQUESTED** [review]
seems a bit silly. maybe a little less silly-ness

**Review by bparker12 — APPROVED** [review]
👍

**Review by joekennerly — APPROVED** [review]

**Comment by joekennerly** [comment]
👍

**Pull request merged**
